#
#  ______                           __
# /_  __/___  _________ _____  ____/ /___  ____ ___
#  / / / __ \/ ___/ __ `/ __ \/ __  / __ \/ __ `__ \
# / / / /_/ / /  / /_/ / / / / /_/ / /_/ / / / / / /
#/_/ / .___/_/   \__,_/_/ /_/\__,_/\____/_/ /_/ /_/
#   /_/
#
#Version 1.0.3
#language Setting/语言设置
language: "zh"
#Transfer settings/传送设置
teleport:
  #Transmission range/传送范围
  range: 5000
  #Need to wait time/需要等待的时间
  #Unit: seconds/单位为：秒
  countdown: 5